### ISSUE TITLE
Consolidate inversion lemmas

### ISSUE THREAD

**Issue by haselwarter** [TheoWinterhalter/formal-type-theory#26]
Currently there's both `formalization/inversion.v` and `formalization/ptt_inversion.v`. We could have just one of them, preferably configuration-agnostic.

**Comment by TheoWinterhalter** [comment]
They are separated for historical reasons, `ptt_inversion.v` was used to prove sanity, and sanity was used in `inversion.v`. We need to investigate that as it might no longer be the case.

**Comment by TheoWinterhalter** [comment]
With the current version, we no longer feature both files. However, we lost all the previous inversion principles that were proved using sanity.
